name: autocheck

on:
  push:
  pull_request:
  watch:
    types: [ started ]
  schedule:
    - cron: 0 23  * * *

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
          python-version: '3.8'
    - name: 'Install dependencies'
      run: python -m pip install --upgrade requests
           |python -m pip install --upgrade pip
           |apt-get install pip3
           |pip3 install requests
    - name: sign
      env:
       account: ${{ secrets.account }}
       pwd: ${{ secrets.pwd }}
       TG_TOKEN: ${{ secrets.TG_TOKEN }}
       CHAT_ID: ${{ secrets.CHAT_ID }}
       lng: ${{ secrets.lng }}
       lat: ${{ secrets.lat }}
       DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
       DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
      run: |
       python3 check.py
